### ISSUE TITLE
Bug : Hit and Miss Ratio gets printed as whole number

### ISSUE THREAD

**Issue by suvojit-0x55aa** [shin-migami/vmPrism#15]
Hit and Miss Ratio should get printed as decimal(double) or as percentage(3 point precision would do fine)

**Comment by vampire-slayer** [comment]
I have opened two pull requests fixing the bug.

**Comment by suvojit-0x55aa** [comment]
Thanks @vampire-slayer for your valueable contribution. If you dont mind you can take a look at other issues.

**Comment by vampire-slayer** [comment]
Sure!
